# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      files_glob:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Files to compile (no extension!)'
        # Default value if no value is explicitly provided
        default: '[0-8]-*'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: p4010/rmarkdown:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: List files
      run: ls -l
    - name: Current dir
      run: echo "Current directory:" $(pwd)
    - name: Test Rscript
      run: echo $(Rscript --version)
    - name: Compile pdf
      run: GITHUB_WORKSPACE=$PWD Docker/make_pdf.R ${{ inputs.files_glob }}.Rmd
    - name: List files (after)
      run: ls -l
    - name: Create Package
      run: zip S4M.zip ${{ inputs.files_glob }}.pdf
    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      with:
        name: S4M
        path: |
          ${{ inputs.files_glob }}.pdf
          S4M.zip
          
