# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      files_glob:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Files to compile (no extension!)'
        # Default value if no value is explicitly provided
        default: '[0-8]-*'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: p4010/rmarkdown:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test Rscript
      run: echo $(Rscript --version)
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(git describe --long --dirty=X)
      shell: bash
    - name: Compile pdf
      run: GITHUB_WORKSPACE=$PWD Docker/make_pdf.R ${{ inputs.files_glob }}.Rmd
    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      with:
        name: S4M_${{ steps.get_version.outputs.VERSION }}
        path: |
          ${{ inputs.files_glob }}.pdf
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.get_version.outputs.VERSION }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload S4M artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./S4M.zip
        asset_name: S4M.zip
        asset_content_type: application/zip
