# This is a basic workflow that is manually triggered

name: Automatic PDF generation

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags: "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Compile the Rmd files into PDFs, make a release and upload the zip
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: p4010/rmarkdown:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Get version
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
    - name: git safe directory
      run: git config --global --add safe.directory $(pwd)

    - name: Compile pdf
      run: GITHUB_WORKSPACE=$PWD GITHUB_VERSION=$VERSION Docker/make_pdf.R [0-8]-*.Rmd
        
    - name: Create zip
      run: zip S4M_${{ env.VERSION }}.zip [0-8]-*.pdf
          
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: S4M, ${{ env.VERSION }}
        tag_name: S4M_${{ env.VERSION }}
        body: |
          The following files contain:
          - `S4M_${{ env.VERSION }}`: all the PDF files, zipped in one archive
          - `source code`: the original repo content, zipped or tarballed (but **NO PDFs!**)
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Publish S4M artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./S4M_${{ env.VERSION }}.zip
        asset_name: S4M_${{ env.VERSION }}.zip
        asset_content_type: application/zip
