# This is a basic workflow that is manually triggered

name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      files_glob:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Files to compile (no extension!)'
        # Default value if no value is explicitly provided
        default: '[0-8]-*'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set current date as env variable
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: git safe directory
      run: git config --global --add safe.directory $(pwd)
      
    - name: Get the version
      id: get_version
      run: echo "::set-output name=VERSION::$(git describe --long)"
      
    - name: Create zip
      run: zip test_${{ steps.date.outputs.date }}.zip ${{ inputs.files_glob }}.Rmd
          
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Test version
        tag_name: test_${{ steps.date.outputs.date }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Publish S4M artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./test_${{ steps.date.outputs.date }}.zip
        asset_name: test_${{ steps.date.outputs.date }}.zip
        asset_content_type: application/zip
